config/routes.rb
Rails.application.routes.draw do

  resources :leads

  root 'static_pages#home'
  get 'static_pages/home'
  get 'furniture' => 'static_pages#furniture'
  get 'real_estate' => 'static_pages#real_estate'
  get 'pricing' => 'static_pages#pricing'
  get 'home' => 'static_pages#home'
  resources :messages

end

app/models/lead.rb
class Lead < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base

end

app/models/mms.rb
class Mms < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:show, :edit, :update, :destroy]

  # GET /leads
  # GET /leads.json
  def index
    @leads = Lead.all
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(lead_params)

    respond_to do |format|
      if @lead.save
        format.html { redirect_to @lead, notice: "Thanks! We'll be in touch" }
        format.json { render :show, status: :created, location: @lead }
      else
        format.html { render :new }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leads/1
  # PATCH/PUT /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lead_params
      params.require(:lead).permit(:name, :email, :phone, :company)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1 GET /messages/1.json
  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    #@message = Message.new(convert_data_uri_to_upload(message_params))

    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
         Delayed::Job.enqueue UploadSendJob.new(@message.id)

        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end



  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:phone, :file)
    end



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
		@message = Message.new
  end

  def furniture
  	@message = Message.new
  end

  def real_estate
  	@message = Message.new
  end


  def pricing
  	@lead = Lead.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Send to Phone - Let Customers Push Information to their Phone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content ="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

  <!-- Bootstrap -->
  <link href="/assets/bootstrap.min.css" rel="stylesheet">

  <!-- Custom Styles -->
  <link href="/assets/application.css" rel="stylesheet">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>
<body>

<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "SendtoPhone", home_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Login</a></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- Page Content -->
<div class="container">

<%= yield %>

</div><!-- /.container -->

<footer class="footer">
    <p class="text-muted"><small>&copy; SendtoPhone 2015</small></p>

</footer>

</body>
</html>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-63788601-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/leads/_form.html.erb
<%= form_for(@lead) do |f| %>
  <% if @lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
      <% @lead.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leads/edit.html.erb
<h1>Editing Lead</h1>

<%= render 'form' %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Leads</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leads.each do |lead| %>
      <tr>
        <td><%= lead.name %></td>
        <td><%= lead.email %></td>
        <td><%= lead.phone %></td>
        <td><%= lead.company %></td>
        <td><%= link_to 'Show', lead %></td>
        <td><%= link_to 'Edit', edit_lead_path(lead) %></td>
        <td><%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lead', new_lead_path %>

app/views/leads/new.html.erb
<h1>Pardon Our Dust!</h1>

<p>We're working on Send to Phone, and it should be ready in the next month or so.  If you'd like to be contacted, please fill out the form below.</p>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/leads/show.html.erb
<h2 id="notice"><%= notice %></h2>

<p>Here is the information you provided:</p>
<p>
  <strong>Name:</strong>
  <%= @lead.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @lead.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @lead.phone %>
</p>

<p>
  <strong>Company:</strong>
  <%= @lead.company %>
</p>
<br><br><br><br>
<%= link_to 'Home', home_path, class: "navlink" %>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :file %><br>
    <%= f.text_field :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>Phone</th>
      <th>File</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.phone %></td>
        <td><%= message.file %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phone:</strong>
  <%= @message.phone %>
</p>

<p>
  <strong>File:</strong>
  <%= @message.file %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/static_pages/furniture.html.erb
  <h1 class="center">Don't get lost in a crowded inbox!<h1>
  <h2 class="center">Get well-qualified phone leads with<br><img style="display:block; text-align: center;
    margin: 20px auto; text-align:center;" src="<%= asset_path('SendtoPhoneLogo.png') %>" width="auto"></h2>
  <h1 class="center">Try it now:</h1>

    <div class="row">
      <div class="col-md-3 box-border col-md-offset-2" id="sendtophone">
          <div class="row"><div class="col-md-12"><img src="<%= asset_path('bed.jpg') %>" width="150px"></div></div>
          <div class="row">
            <div class="col-md-12">
              <h4>Anders Bed</h4>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">$1,099 - $1,899</div>
          </div>
          <div class="row">
            <div class="col-md-12">5 sizes, 2 woods</div>
          </div>
          <div class="row">
            <div class="col-md-12"><img src="<%= asset_path('star_rating.png') %>"> (33)</div>
          </div>

      </div>
      <div class="col-md-7">
        <img src="<%= asset_path('arrow.png') %>" class="pull-left" style="padding-top: 200px;">
        <button type="button" class="btn btn-success btn-lg pull-left" id="modal_open" style="margin-top: 100px; font-size: 30px;" role="button"><!-- <i class="glyphicon glyphicon-phone"></i> --> Send to Phone</button>
      </div>
    </div>


    <div id="modal_wrapper">
      <div id="modal_window">

        <div style="text-align: right;"><a id="modal_close" href="#">close <b>X</b></a></div>

        <p>Complete the form below to send an MMS with this product information to your phone:</p>

        <%= form_for @message, html: { id: "modal_feedback", class: "directUpload"} do |f| %>
          <%= f.label :phone %>
          <%= f.text_field :phone, autofocus: true, required: true %>
          <br><br>
          <%= f.submit "Send to Phone", class: "btn btn-primary", name: "feedbackForm" %>
          <%= f.hidden_field :file %>  <!-- Adding file to form as dataURL -->

        <% end %>

      </div> <!-- #modal_window -->
    </div> <!-- #modal_wrapper -->

    <div id="modal_wrapper_success">
      <div id="modal_window_success">

        <div style="text-align: right;"><a id="modal_close_success" href="#">close <b>X</b></a></div>

        <p class="success">Success! The information is being sent to you as a text message</p>

      </div> <!-- #modal_window_success -->
    </div> <!-- #modal_wrapper_success -->





<h2>SendToPhone lets customers text themselves vehicle information from your website.</h2>
  <ul>
    <li><h3>Customers who use SendToPhone are close to making a purchase decision.</h3></li>
    <li><h3>SendToPhone sends <i>you</i> their <u>phone number</u> and <u>vehicle they're interested in.</h3></u></li>

  </ul>


<h2>What about billing?</h2>

  <ul>
    <li><h3>Get up to 500 phone leads at only $0.60 per lead</h3></li>
    <li><h3>SendToPhone is capped at $299 / month for our basic plan</h3></li>
  </ul>

  <hr class="featurette-divider">
  <div class="well">
        <h2 class="text-center" style="padding-bottom:20px;">Ready to get phone leads of customers who are ready to purchase?</h2>
        <div class="row">
        <div class="col-md-4 col-md-offset-2 ">
            <div class="panel panel-primary text-center">
                <div class="panel-heading">
                    <h3 class="panel-title">Basic</h3>
                </div>
                <div class="panel-body">
                    <span class="price">$0.60 per lead</span>
                </div>
                <ul class="list-group">

                    <li class="list-group-item">Up to <strong>500</strong> Texts per month<br><br></li>
                    <li class="list-group-item">
                    <%= link_to "Sign up!", pricing_path, class: "btn btn-primary" %>


                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-primary text-center">
                <div class="panel-heading">
                    <h3 class="panel-title">Enterprise</h3>
                </div>
                <div class="panel-body">
                   Custom
                </div>
                <ul class="list-group">

                    <li class="list-group-item">As many as you need.<br> Per text pricing.</li>
                    <li class="list-group-item">
                    <%= link_to "Let's Chat", pricing_path, class: "btn btn-primary" %>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- /.row -->
  </div>






<%= javascript_include_tag('feedback-modal-window', 'html2canvas','sendtophone', 'moment') %>

app/views/static_pages/home.html.erb
  <h1 class="center">Don't get lost in a crowded inbox!<h1>
  <h2 class="center">Get well-qualified phone leads with<br><img style="display:block; text-align: center;
    margin: 20px auto; text-align:center;" src="<%= asset_path('SendtoPhoneLogo.png') %>" width="auto"></h2>
  <h1 class="center">Try it now:</h1>

    <div class="row">
      <div class="col-md-4 box-border" id="sendtophone">
          <div class="row"><div class="col-md-12"><img src="<%= asset_path('mercedes.jpg') %>" width="250px"></div></div>


          <div class="row"><div class="col-md-12">
          <h4>2010 Mercedes-Benz C-Class C320 Coupe</h4></div></div>
          <div class="row">
            <div class="col-md-6 bold">Price</div>
            <div class="col-md-6">$8,888</div>
          </div>
          <div class="row">
            <div class="col-md-6 bold">Engine:</div>
            <div class="col-md-6">3.2L V-6</div>
          </div>
          <div class="row">
            <div class="col-md-6 bold">Transmission:</div>
            <div class="col-md-6">5-Speed Automatic</div>
          </div>
          <div class="row">
            <div class="col-md-6 bold">Mileage:</div>
            <div class="col-md-6">76,663 miles</div>
          </div>
          <div class="row">
            <div class="col-md-6 bold">MPG Range:</div>
            <div class="col-md-6">17/25</div>
          </div>
          <div class="row">
            <div class="col-md-6 bold">Stock</div>
            <div class="col-md-6">#22308G</div>
          </div>

      </div>
      <div class="col-md-7">
        <img src="<%= asset_path('arrow.png') %>" class="pull-left" style="padding-top: 300px;">
        <button type="button" class="btn btn-success btn-lg pull-left" id="modal_open" style="margin-top: 200px; font-size: 30px;" role="button"><!-- <i class="glyphicon glyphicon-phone"></i> --> Send to Phone</button>
      </div>
    </div>


    <div id="modal_wrapper">
      <div id="modal_window">

        <div style="text-align: right;"><a id="modal_close" href="#">close <b>X</b></a></div>

        <p>Complete the form below to send an MMS with this product information to your phone:</p>

        <%= form_for @message, html: { id: "modal_feedback", class: "directUpload"} do |f| %>
          <%= f.label :phone %>
          <%= f.text_field :phone, autofocus: true, required: true %>
          <br><br>
          <%= f.submit "Send to Phone", class: "btn btn-primary", name: "feedbackForm" %>
          <%= f.hidden_field :file %>  <!-- Adding file to form as dataURL -->

        <% end %>

      </div> <!-- #modal_window -->
    </div> <!-- #modal_wrapper -->

    <div id="modal_wrapper_success">
      <div id="modal_window_success">

        <div style="text-align: right;"><a id="modal_close_success" href="#">close <b>X</b></a></div>

        <p class="success">Success! The information is being sent to you as a text message</p>

      </div> <!-- #modal_window_success -->
    </div> <!-- #modal_wrapper_success -->





<h2>SendToPhone lets customers text themselves vehicle information from your website.</h2>
  <ul>
    <li><h3>Customers who use SendToPhone are close to making a purchase decision.</h3></li>
    <li><h3>SendToPhone sends <i>you</i> their <u>phone number</u> and <u>vehicle they're interested in.</h3></u></li>

  </ul>


<h2>What about billing?</h2>

  <ul>
    <li><h3>Get up to 500 phone leads at only $0.60 per lead</h3></li>
    <li><h3>SendToPhone is capped at $299 / month for our basic plan</h3></li>
  </ul>

  <hr class="featurette-divider">
  <div class="well">
        <h2 class="text-center" style="padding-bottom:20px;">Ready to get phone leads of customers who are ready to purchase?</h2>
        <div class="row">
        <div class="col-md-4 col-md-offset-2 ">
            <div class="panel panel-primary text-center">
                <div class="panel-heading">
                    <h3 class="panel-title">Basic</h3>
                </div>
                <div class="panel-body">
                    <span class="price">$299<sup>99</sup>
</span>
                    <span class="period">per month</span>
                </div>
                <ul class="list-group">

                    <li class="list-group-item">Up to <strong>500</strong> Texts per month<br><br></li>
                    <li class="list-group-item">
                    <%= link_to "Sign up!", pricing_path, class: "btn btn-primary" %>


                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-primary text-center">
                <div class="panel-heading">
                    <h3 class="panel-title">Enterprise</h3>
                </div>
                <div class="panel-body">
                   Custom
                </div>
                <ul class="list-group">

                    <li class="list-group-item">As many as you need.<br> Per text pricing.</li>
                    <li class="list-group-item">
                    <%= link_to "Let's Chat", pricing_path, class: "btn btn-primary" %>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- /.row -->
  </div>






<%= javascript_include_tag('feedback-modal-window', 'html2canvas','sendtophone', 'moment') %>

app/views/static_pages/pricing.html.erb
<!-- <div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h1 class="center">Pardon Our Dust!</h1>

		<p class= "margin-bottom">We're working on Send to Phone, and it should be ready in the next month or so.<br><br>
		Get on our list for the beta!</p>

		<%= form_for(@lead) do |f|%>
			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :phone, "Phone (Optional)" %>
			<%= f.text_field :phone %>

			<%= f.label :company, "Company (Optional)" %>
			<%= f.text_field :company %>

			<%= f.label :comment, "Comments" %>
			<%= f.text_area :comment %>

			<%= f.submit "Get Notified", class: "btn btn-primary btn-large bold-larger" %>
		<% end %>
	</div>
</div> -->


<div id="wufoo-q1m10uh40j7mamx">
Fill out my <a href="https://russelltest.wufoo.com/forms/q1m10uh40j7mamx">online form</a>.
</div>
<div id="wuf-adv" style="font-family:inherit;font-size: small;color:#a7a7a7;text-align:center;display:block;">HTML Forms powered by <a href="http://www.wufoo.com">Wufoo</a>.</div>
<script type="text/javascript">var q1m10uh40j7mamx;(function(d, t) {
var s = d.createElement(t), options = {
'userName':'russelltest',
'formHash':'q1m10uh40j7mamx',
'autoResize':true,
'height':'480',
'async':true,
'host':'wufoo.com',
'header':'show',
'ssl':true};
s.src = ('https:' == d.location.protocol ? 'https://' : 'http://') + 'www.wufoo.com/scripts/embed/form.js';
s.onload = s.onreadystatechange = function() {
var rs = this.readyState; if (rs) if (rs != 'complete') if (rs != 'loaded') return;
try { q1m10uh40j7mamx = new WufooForm();q1m10uh40j7mamx.initialize(options);q1m10uh40j7mamx.display(); } catch (e) {}};
var scr = d.getElementsByTagName(t)[0], par = scr.parentNode; par.insertBefore(s, scr);
})(document, 'script');</script>

app/views/static_pages/real_estate.html.erb
  <h1 class="center">Don't get lost in a crowded inbox!<h1>
  <h2 class="center">Get well-qualified phone leads from your website with<br><img style="display:block; text-align: center;
    margin: 20px auto; text-align:center;" src="<%= asset_path('SendtoPhoneLogo.png') %>" width="auto"></h2>
  <h1 class="center">Try it now:</h1>

    <div class="row">
      <div class="col-md-4 box-border" id="sendtophone">
          <div class="row"><div class="col-md-12"><img src="<%= asset_path('house.jpg') %>" width="250px"></div></div>

          <div class="row"><div class="col-md-12">
          <h4>Novato: 650 Canyon Road</h4></div></div>
          <div class="row">
            <div class="col-md-6 bold">Price:</div>
            <div class="col-md-6">$835,000</div>
          </div>
          <div class="row">
            <div class="col-md-6 bold">Bedrooms:</div>
            <div class="col-md-6">4</div>
          </div>
          <div class="row">
            <div class="col-md-6 bold">Bathrooms:</div>
            <div class="col-md-6">3</div>
          </div>
          <div class="row">
            <div class="col-md-6 bold">Size:</div>
            <div class="col-md-6">2,397 sq. ft.</div>
          </div>
          <div class="row">
            <div class="col-md-12"><span style="font-size:16px;">Nine foot ceilings throughout.<br>Gourmet chef's kitchen with center island & breakfast area<br> Great Room with stone fireplace adjoins kitchen & eating area</span>
            </div>
          </div>
      </div>
      <div class="col-md-7">
        <img src="<%= asset_path('arrow.png') %>" class="pull-left" style="padding-top: 300px;">
        <button type="button" class="btn btn-success btn-lg pull-left" id="modal_open" style="margin-top: 200px; font-size: 30px;" role="button"><!-- <i class="glyphicon glyphicon-phone"></i> --> Send to Phone</button>
      </div>
    </div>


    <div id="modal_wrapper">
      <div id="modal_window">

        <div style="text-align: right;"><a id="modal_close" href="#">close <b>X</b></a></div>

        <p>Complete the form below to send an MMS with this product information to your phone:</p>

        <%= form_for @message, html: { id: "modal_feedback", class: "directUpload"} do |f| %>
          <%= f.label :phone %>
          <%= f.text_field :phone, autofocus: true, required: true %>
          <br><br>
          <%= f.submit "Send to Phone", class: "btn btn-primary", name: "feedbackForm" %>
          <%= f.hidden_field :file %>  <!-- Adding file to form as dataURL -->

        <% end %>

      </div> <!-- #modal_window -->
    </div> <!-- #modal_wrapper -->

    <div id="modal_wrapper_success">
      <div id="modal_window_success">

        <div style="text-align: right;"><a id="modal_close_success" href="#">close <b>X</b></a></div>

        <p class="success">Success! The information is being sent to you as a text message</p>

      </div> <!-- #modal_window_success -->
    </div> <!-- #modal_wrapper_success -->





<h2>SendToPhone lets customers text themselves house information from your website.</h2>
  <ul>
    <li><h3>Customers who use SendToPhone are close to making a purchase decision.</h3></li>
    <li><h3>SendToPhone sends <i>you</i> their <u>phone number</u> and <u>house they're interested in.</h3></u></li>

  </ul>


<h2>What about billing?</h2>

  <ul>
    <li><h3>Get up to 500 phone leads at only $0.60 per lead</h3></li>
  </ul>

  <hr class="featurette-divider">
  <div class="well">
        <h2 class="text-center" style="padding-bottom:20px;">Ready to get phone leads of customers who are ready to visit a house?</h2>
        <div class="row">
        <div class="col-md-4 col-md-offset-2 ">
            <div class="panel panel-primary text-center">
                <div class="panel-heading">
                    <h3 class="panel-title">Basic</h3>
                </div>
                <div class="panel-body">
                  <span class="price">$0.60 per lead</span>

                </div>
                <ul class="list-group">
                    <li class="list-group-item">Up to <strong>500</strong> Texts per month<br><br></li>
                    <li class="list-group-item">
                    <%= link_to "Sign up!", pricing_path, class: "btn btn-primary" %>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-primary text-center">
                <div class="panel-heading">
                    <h3 class="panel-title">Enterprise</h3>
                </div>
                <div class="panel-body">
                   Custom
                </div>
                <ul class="list-group">

                    <li class="list-group-item">As many as you need.<br> Per text pricing.</li>
                    <li class="list-group-item">
                    <%= link_to "Let's Chat", pricing_path, class: "btn btn-primary" %>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- /.row -->
  </div>






<%= javascript_include_tag('feedback-modal-window', 'html2canvas','sendtophone', 'moment') %>